services:
  traefik:
    image: traefik:v2.10.5
    restart: unless-stopped
    environment:
      TZ: ${GENERIC_TIMEZONE}
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/dynamic_conf.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/logs/access.log"
      - "--accesslog.bufferingsize=1000"
      - "--log.format=json"
      - "--accesslog.format=json"
    labels:
      - "traefik.enable=true"

      # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=authtraefik@docker"
      - "traefik.http.middlewares.authtraefik.basicauth.users=admin:$$apr1$$U21MlNDz$$UUIow5X8TF3qS5Bv5aypI1"

      # Redirección dominio raíz -> flows
      - "traefik.http.middlewares.redirect-to-flows.redirectregex.regex=^https?://[^/]+/(.*)"
      - "traefik.http.middlewares.redirect-to-flows.redirectregex.replacement=https://${SUBDOMAIN_FLOWS}.${DOMAIN_NAME}/$${1}"
      - "traefik.http.middlewares.redirect-to-flows.redirectregex.permanent=true"

      - "traefik.http.routers.redirect-root.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.redirect-root.entrypoints=websecure"
      - "traefik.http.routers.redirect-root.tls=true"
      - "traefik.http.routers.redirect-root.middlewares=redirect-to-flows"
      - "traefik.http.routers.redirect-root.service=noop@internal"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/logs:/logs
      - ./traefik/dynamic_conf.yml:/dynamic_conf.yml:ro
      - ./traefik/certs:/certs:ro
    networks:
      - red_solercia_com_co

  postgres:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=solercia
      - POSTGRES_USER=soler
      - POSTGRES_PASSWORD=SO5!2025
    ports:
      - "5433:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U soler -d solercia"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - red_solercia_com_co

  flows:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=red_solercia_com_co
      - traefik.http.routers.flows.rule=Host(`${SUBDOMAIN_FLOWS}.${DOMAIN_NAME}`)
      - traefik.http.routers.flows.entrypoints=websecure
      - traefik.http.routers.flows.tls=true
      - traefik.http.routers.flows.service=flows@docker
      - traefik.http.routers.flows.middlewares=flows@docker
      - traefik.http.services.flows.loadbalancer.server.port=5678
      - traefik.http.middlewares.flows.headers.stsSeconds=315360000
      - traefik.http.middlewares.flows.headers.browserXssFilter=true
      - traefik.http.middlewares.flows.headers.contentTypeNosniff=true
      - traefik.http.middlewares.flows.headers.forceSTSHeader=true
      - traefik.http.middlewares.flows.headers.sslHost=${DOMAIN_NAME}
      - traefik.http.middlewares.flows.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.flows.headers.stsPreload=true

    environment:
      - N8N_HOST=${SUBDOMAIN_FLOWS}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN_FLOWS}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_EDITOR_BASE_URL=https://${SUBDOMAIN_FLOWS}.${DOMAIN_NAME}/

      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=solercia
      - DB_POSTGRESDB_USER=soler
      - DB_POSTGRESDB_PASSWORD=SO5!2025
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - red_solercia_com_co


  #incluir el website de solercia.com.co
  solercia-web:
    image: nginx:1.27-alpine
    container_name: solercia-web
    restart: unless-stopped
    volumes:
      - ./solercia-web/dist/solercia-web/browser:/usr/share/nginx/html:ro
      - ./solercia-web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=red_solercia_com_co
      - traefik.http.routers.website.rule=Host(`${SUBDOMAIN_WEB}.${DOMAIN_NAME}`)
      - traefik.http.routers.website.entrypoints=websecure
      - traefik.http.routers.website.service=website@docker  
      - traefik.http.routers.website.tls=true
      - traefik.http.services.website.loadbalancer.server.port=80
    networks:
      - red_solercia_com_co

  # Servicio Bolt AI
  bolt:
    image: bolt-ai:development
    build:
      context: ./bolt.diy
      target: bolt-ai-development
    container_name: bolt-ai
    restart: unless-stopped
    env_file: './bolt.diy/.env'
    environment:
      - NODE_ENV=development
      - VITE_HMR_PROTOCOL=ws
      - VITE_HMR_HOST=bolt.${DOMAIN_NAME}
      - VITE_HMR_PORT=5173
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PORT=5173

      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - './bolt.diy:/app'
      - './bolt.diy/node_modules:/app/node_modules'
    labels:
      - traefik.enable=true
      - traefik.docker.network=red_solercia_com_co
      - traefik.http.routers.bolt.rule=Host(`bolt.${DOMAIN_NAME}`)
      - traefik.http.routers.bolt.entrypoints=websecure
      - traefik.http.routers.bolt.tls=true
      - traefik.http.routers.bolt.service=bolt@docker
      - traefik.http.services.bolt.loadbalancer.server.port=5173
      - traefik.http.middlewares.bolt.headers.stsSeconds=315360000
      - traefik.http.middlewares.bolt.headers.browserXssFilter=true
      - traefik.http.middlewares.bolt.headers.contentTypeNosniff=true
      - traefik.http.middlewares.bolt.headers.forceSTSHeader=true
      - traefik.http.middlewares.bolt.headers.sslHost=${DOMAIN_NAME}
      - traefik.http.middlewares.bolt.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.bolt.headers.stsPreload=true
    command: pnpm run dev --host 0.0.0.0
    networks:
      - red_solercia_com_co


volumes:
  n8n_data:
  traefik_data:
  postgres-data:


# Definición de redes
networks:
  red_solercia_com_co:
    name: red_solercia_com_co
    driver: bridge